/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ygqgikdsrbcryfbhtzeo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlncWdpa2RzcmJjcnlmYmh0emVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NTY3OTcsImV4cCI6MjA3NTEzMjc5N30.EiNuHtgpNFuF5-2cfLK8JRQoG-JEplXLpk64l1gwZU4"